config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :rooms
  end
  resources :rentals
  resources :rooms do
    resources :bookings
  end
 
   devise_scope :user do
    authenticated :user do
      root :to => 'rooms#index'
    end
    unauthenticated :user do
      root :to => 'rentals#index', as: :unauthenticated_root
  end
end

 

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :room
	belongs_to :user
end

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :title, :description, :price, :image, presence: true 

  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :rooms
  has_many :clients, class_name:"User", through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_filter :authenticate_user!
  def new
    @booking = Booking.new
    @room = Room.find(params[:room_id])
    @user = User.find(params[:user_id])
  end

  def create
  end

  def index
  end

  def destroy
  end

  def show
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @rooms = Room.all
    @new_room = Room.new
    @user = current_user
  end

  def new
    @room = Room.new
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.js
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @room = Room.find(params[:id])
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash.notice = "Successfully Deleted"
    redirect_to user_rooms_path(current_user.id)
  end

  def show
    @new_room = Room.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def create
    @user = current_user
    @new_room = Room.new(room_params)
    @new_room.user_id = params[:user_id]
    if @new_room.save
      flash[:msg] = "Successfully created"
      redirect_to user_rooms_path(current_user.id)
    else
      flash[:msg] = "cannot create"
      render  partial: 'form'
    end

  end

  def update
    @room = Room.find(params[:id])
    @room.update(room_params)
    flash[:msg]= "Successfully #{@room.title} Updated !!"
    redirect_to user_rooms_path(current_user.id)
  end

  def room_params
    params.require(:room).permit(:title, :location, :available, :description, :price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/_footer.html.erb
<div class ="navbar navbar-default navbar-fixed-bottom">
	<p class="navbar-text pull-right">
		
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rental</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:msg] %>
			<div class  = "alert alert-warning">
			<%= flash[:msg]%>
		</div>
		<% end %>

	<%= yield %>

	<%= render partial: "layouts/footer"%>

</body>
</html>

app/views/rentals/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Rent</a>
      <%=image_tag("rent.jpeg", :class=>"img-circle", :width=> "50px", :height=> "50px")%> 
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><span class = "signup"> 
          <%= link_to "Sign Up",  new_user_registration_path, class: "navbar-link my-link"%> </span></li> 
        <li><span class ="signup"><%= link_to "Login",  new_user_session_path, class: "navbar-link my-link" %></span></li>
      </ul>
    </div>
  </div>
</nav>
<div class= "container-fluid-home">
  <div class = "col-sm-12">
    <h1> Find Homely Environment</h1>
    <h2> At Cheapest Rate</h2>
  </div>
  
</div>

app/views/rooms/_form.html.erb
 <div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <h4 class="modal-title"><strong>Room Details</strong></h4>
      </div>
      <div class="modal-body">
        
        <%= form_for [ @user, @new_room ] do |f| %>
          <ul>
            <% @new_room.errors.full_messages.each do |error| %>
            <li><%= error %></li>
            <% end %>
          </ul>
          <p>
            <%= f.label :title %><br/>
            <%= f.text_field :title, :required => true%>
          </p>
          <p>
            <%= f.label :location %><br/>
            <%= f.text_field :location, :required => true%>
          </p>
          <p>
            <%= f.label :available_rooms %><br/>
            <%= f.text_field :available, :required => true%>
          </p>
          <p>
            <%= f.label :description %><br/>
            <%= f.text_area :description, :required => true %>
          </p>  
          <p>
            <%= f.label :price %><br/>
            <%= f.text_field :price, :required => true %>
          </p>  
           <p>
            <%= f.label :image %><br/>
            <%= f.file_field :image  %>
          </p>  
          <p>
            <%= f.submit %>
          </p>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
</div>

app/views/rooms/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Rent</a>
      <%=image_tag("rent.jpeg", :class=>"img-circle", :width=> "50px", :height=> "50px")%> 
    </div>
    <div>
      <ul class="nav navbar-nav">
         <li><span > 
          <%= link_to "Home", root_path, :class=> "link" %> </span></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><span > 
          <%= link_to "Post Room", new_user_room_path(current_user.id), :type=>"button", :class=>"btn btn-info btn-lg", data: {toggle: "modal", target: "#myModal"}, remote: true %> </span></li> 
      </ul>
    </div>
  </div>
</nav>
<%= render partial: 'form'%> 

app/views/rooms/_new.html.erb
<%= render partial: 'header' %>
<div class = "container">
	<h2>Post Room</h2>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/destroy.html.erb
<h1>Rooms#destroy</h1>
<p>Find me in app/views/rooms/destroy.html.erb</p>

app/views/rooms/edit.html.erb
<div class = "container">
	<%= render partial: 'form' %>
</div>

app/views/rooms/index.html.erb
<%= render partial: 'header' %>
<h2> Available Rooms </h2>
<div class="row">
  <% @rooms.each_with_index do |r,i| %>
    <div class="col-sm-6 col-md-4" style="<%= 'clear:both;' if i%3 == 0 %>">
      <div class="thumbnail-index">
      	
  			<%= image_tag r.image.url(:medium), class: "image"%>
  			<div class="caption">
  			<h3><%= r.title %></h3> <br>
  				 Rate : <%= r.price %>
  			<p><%= link_to "View Details", user_room_path(r.user_id, r.id), class: "btn btn-primary", role: "button" %></p>
        </div>
      </div>
    </div>
    <% end %>
</div>
		

      
      
        
        
        

app/views/rooms/new.html.erb
<%= render partial: 'header' %>
<div class = "container">
	<h2>Post Room</h2>
	 
</div>

app/views/rooms/new.js.erb
$("#myModal").html("<%= j(render 'new')%>")
	$("#myModal").modal("show")

app/views/rooms/show.html.erb
<%= render partial: 'header' %>
<div class = "container">
	<div class = "col-sm-4">
		<h1><%= @new_room.title %></h1>
		<p>Description: <%= @new_room.description %></p>
		<p>Price: <%= @new_room.price %></p>
		<% if @new_room.user == current_user %>
			<%= link_to "DELETE", user_room_path(@new_room.user_id,@new_room),  class: "btn btn-primary", method: :delete, data: {confirm: "Really delete the post?"} %>
			<%= link_to "EDIT", edit_user_room_path(@new_room.user_id, @new_room.id), :type=>"button", :class=> "btn btn-primary", data: {toggle: "modal", target: "#myModal"}, remote: true %>
		<% end %>
	</div>
	<div class = "col-sm-8">
		<%= image_tag @new_room.image.url, class: "img-thumbnail" %>
	</div>
</div>
<%= render partial: 'form' %>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>